/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.11.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bednarczuk.voizilla.data.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Strefa
 */
@ApiModel(description = "Strefa")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-07-22T20:17:00.244187+02:00[Europe/Warsaw]")
public class Zone {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = null;

  public static final String SERIALIZED_NAME_ALLOWED_AREAS = "allowedAreas";
  @SerializedName(SERIALIZED_NAME_ALLOWED_AREAS)
  private List<Polygon> allowedAreas = new ArrayList<Polygon>();

  public static final String SERIALIZED_NAME_EXCLUDED_AREAS = "excludedAreas";
  @SerializedName(SERIALIZED_NAME_EXCLUDED_AREAS)
  private List<Polygon> excludedAreas = null;

  public Zone id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Identyfikator obiektu
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Identyfikator obiektu")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Zone name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Nazwa
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Nazwa")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Zone allowedAreas(List<Polygon> allowedAreas) {
    this.allowedAreas = allowedAreas;
    return this;
  }

  public Zone addAllowedAreasItem(Polygon allowedAreasItem) {
    this.allowedAreas.add(allowedAreasItem);
    return this;
  }

   /**
   * Dozwolone obszary
   * @return allowedAreas
  **/
  @ApiModelProperty(required = true, value = "Dozwolone obszary")
  public List<Polygon> getAllowedAreas() {
    return allowedAreas;
  }

  public void setAllowedAreas(List<Polygon> allowedAreas) {
    this.allowedAreas = allowedAreas;
  }

  public Zone excludedAreas(List<Polygon> excludedAreas) {
    this.excludedAreas = excludedAreas;
    return this;
  }

  public Zone addExcludedAreasItem(Polygon excludedAreasItem) {
    if (this.excludedAreas == null) {
      this.excludedAreas = new ArrayList<Polygon>();
    }
    this.excludedAreas.add(excludedAreasItem);
    return this;
  }

   /**
   * Wykluczene obszary
   * @return excludedAreas
  **/
  @ApiModelProperty(value = "Wykluczene obszary")
  public List<Polygon> getExcludedAreas() {
    return excludedAreas;
  }

  public void setExcludedAreas(List<Polygon> excludedAreas) {
    this.excludedAreas = excludedAreas;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Zone zone = (Zone) o;
    return Objects.equals(this.id, zone.id) &&
        Objects.equals(this.name, zone.name) &&
        Objects.equals(this.allowedAreas, zone.allowedAreas) &&
        Objects.equals(this.excludedAreas, zone.excludedAreas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, allowedAreas, excludedAreas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Zone {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    allowedAreas: ").append(toIndentedString(allowedAreas)).append("\n");
    sb.append("    excludedAreas: ").append(toIndentedString(excludedAreas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

